### ISSUE TITLE
Certificate type conversion.

### ISSUE THREAD

**Issue by kennethtipton** [gregtwallace/certwarden#32]
acme.sh can convert its certificate to different types (e.g. pfx PKCS #12 ) is there a way to do this from your interface

**Comment by gregtwallace** [comment]
This is not currently available natively.  I considered adding it but ended up doing the conversion in the client script with OpenSSL: https://github.com/gregtwallace/certificate-scripts/blob/master/lego-unifi-controller.sh

This seemed like a more sane option since there are a number of potential manipulations, but I certainly haven't ruled out adding something.
